spring:
  application:
    name: BuildFlow
  security:
    enabled: false # Custom config to enable/disable security

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,logfile
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: ${LOG_DIR:logs}/${LOG_FILE:build-flow}-${ACTIVE_PROFILE:default}-main.log

server:
  port: 8080
