spring:
  application:
    name: BuildFlow
  security:
    enabled: false # Custom config to enable/disable security
  datasource:
    url: jdbc:h2:file:./data/buildflow-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,logfile
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: ${LOG_DIR:logs}/${LOG_FILE:build-flow}-${ACTIVE_PROFILE:default}-main.log

server:
  port: 8080
