spring:
  application:
    name: BuildFlow
  security:
    enabled: true # Custom security toggle
  # H2 file-based database for development - persistent across restarts
  datasource:
    url: jdbc:h2:file:./data/buildflow-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # H2 console enabled for development - database inspection and queries
  h2:
    console:
      enabled: true
      path: /h2-console
  # JPA settings for development - auto-update schema
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

# Management endpoints for development - expose more endpoints for debugging
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env
  endpoint:
    health:
      show-details: always

# Development server port
server:
  port: 8080

app:
  jwt:
    secret: mySecretKeyForJWTTokensInBuildFlowApplication
    expiration: 86400000 # 24 hours in milliseconds
  admin:
    initialize: true
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:BuildFlow_1st_AdminPassword}
    email: ${ADMIN_EMAIL:hamidreza74hrr@yahoo.com}
  users:
    mock:
      enabled: true
      roles:
        USER:
          count: 10
        PREMIUM_USER:
          count: 5
