### Health endpoint
GET {{base_url}}/actuator/health

### Info endpoint
GET {{base_url}}/actuator/info

### Metrics endpoint
GET {{base_url}}/actuator/metrics

### Prometheus endpoint
GET {{base_url}}/actuator/prometheus

### Env endpoint
GET {{base_url}}/actuator/env

### Logfile endpoint
GET {{base_url}}/actuator/logfile
