name: Security Scan

on:
  schedule:
    # Run security scan weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  security-scan:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Make Maven wrapper executable
      run: chmod +x mvnw
      
    - name: Run Maven dependency check
      run: |
        ./mvnw org.owasp:dependency-check-maven:check \
          -DfailBuildOnCVSS=8 \
          -DskipTestScope=false || echo "Dependency check completed with warnings"
        
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Run npm audit
      working-directory: ./frontend
      run: |
        npm audit --audit-level=high --json > npm-audit.json || echo "npm audit completed with warnings"
        npm audit --audit-level=high || echo "npm audit completed with warnings"
        
    - name: Upload dependency check reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          target/dependency-check-report.html
          frontend/npm-audit.json
        retention-days: 14
        
  codeql-analysis:
    name: CodeQL Security Analysis
    runs-on: ubuntu-latest
    
    permissions:
      actions: read
      contents: read
      security-events: write
      
    strategy:
      matrix:
        language: [ 'java', 'javascript' ]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        
    - name: Setup Java 21 (for Java analysis)
      if: matrix.language == 'java'
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Java project (for CodeQL analysis)
      if: matrix.language == 'java'
      run: |
        chmod +x mvnw
        ./mvnw clean compile -DskipTests
        
    - name: Setup Node.js (for JavaScript analysis)
      if: matrix.language == 'javascript'
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Build frontend (for CodeQL analysis)
      if: matrix.language == 'javascript'
      working-directory: ./frontend
      run: |
        npm ci
        npm run build
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3